FROM arm64v8/alpine:3.13@sha256:360e3ef2bc03ac09862f9589b6123d3b410eed21f80d4d0c1f90899e33f5e734

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Base" \
  org.opencontainers.image.vendor="Webhippie"

ENV GODEBUG=netdns=go

RUN apk add --no-cache ca-certificates mailcap && \
	echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' >| /etc/nsswitch.conf
