FROM amd64/alpine:3.15@sha256:1e014f84205d569a5cc3be4e108ca614055f7e21d11928946113ab3f36054801

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Base" \
  org.opencontainers.image.vendor="Webhippie"

ENV GODEBUG=netdns=go

RUN apk add --no-cache ca-certificates mailcap && \
	echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' >| /etc/nsswitch.conf
