FROM amd64/alpine:3.13@sha256:def822f9851ca422481ec6fee59a9966f12b351c62ccb9aca841526ffaa9f748

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Base" \
  org.opencontainers.image.vendor="Webhippie"

ENV GODEBUG=netdns=go

RUN apk add --no-cache ca-certificates mailcap && \
	echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' >| /etc/nsswitch.conf
