FROM arm64v8/alpine:3.13@sha256:8f18fae117ec6e5777cc62ba78cbb3be10a8a38639ccfb949521abd95c8301a4

LABEL maintainer="Thomas Boerger <thomas@webhippie.de>" \
  org.opencontainers.image.title="Drone Base" \
  org.opencontainers.image.vendor="Webhippie"

ENV GODEBUG=netdns=go

RUN apk add --no-cache ca-certificates mailcap && \
	echo "@testing http://nl.alpinelinux.org/alpine/edge/testing" >> /etc/apk/repositories && \
    [ ! -e /etc/nsswitch.conf ] && echo 'hosts: files dns' >| /etc/nsswitch.conf
